/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6209254b9a7780e90593a727107f4102)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "RealtimeDurableObject";
	}
	interface Env {
		AVATAR_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		BETTER_AUTH_URL: "http://localhost:5173";
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL">> {}
}
