/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 4681aa27d6f69d8071ab6e0009fda592)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "RealtimeDurableObject" | "FactsDatabase";
	}
	interface Env {
		AVATAR_BUCKET: R2Bucket;
		INGESTION_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		DATABASE_URL: string;
		BETTER_AUTH_URL: string;
		BETTER_AUTH_SECRET: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		CHANNEL3_API_KEY: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		RESEND_API_KEY: string;
		POST_HOG_API_KEY: string;
		VITE_PUBLIC_POSTHOG_KEY: string;
		VITE_PUBLIC_POSTHOG_HOST: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		OPENAI_API_KEY: string;
		JINA_API_KEY: string;
		HUBSPOT_API_KEY: string;
		HUBSPOT_BRAND_OBJECT_TYPE_ID: string;
		HUBSPOT_BRAND_PRODUCT_OBJECT_TYPE_ID: string;
		HUBSPOT_PORTAL_ID: string;
		HUBSPOT_WAITLIST_FORM_ID: string;
		HUBSPOT_CONTACT_US_FORM_ID: string;
		OPENROUTER_API_KEY: string;
		HUBSPOT_BRAND_REQUEST_FORM_ID: string;
		ANTHROPIC_API_KEY: string;
		CHROMA_API_KEY: string;
		CHROMA_TENANT: string;
		CHROMA_DATABASE: string;
		GITHUB_WEBHOOK_SECRET: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		FACTS_DATABASE: DurableObjectNamespace<import("./src/worker").FactsDatabase>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GITHUB_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "CHANNEL3_API_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "RESEND_API_KEY" | "POST_HOG_API_KEY" | "VITE_PUBLIC_POSTHOG_KEY" | "VITE_PUBLIC_POSTHOG_HOST" | "CLOUDFLARE_ACCOUNT_ID" | "OPENAI_API_KEY" | "JINA_API_KEY" | "HUBSPOT_API_KEY" | "HUBSPOT_BRAND_OBJECT_TYPE_ID" | "HUBSPOT_BRAND_PRODUCT_OBJECT_TYPE_ID" | "HUBSPOT_PORTAL_ID" | "HUBSPOT_WAITLIST_FORM_ID" | "HUBSPOT_CONTACT_US_FORM_ID" | "OPENROUTER_API_KEY" | "HUBSPOT_BRAND_REQUEST_FORM_ID" | "ANTHROPIC_API_KEY" | "CHROMA_API_KEY" | "CHROMA_TENANT" | "CHROMA_DATABASE" | "GITHUB_WEBHOOK_SECRET">> {}
}
