/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: e47056a912b8d94c6b9a9172b92b3a40)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "RealtimeDurableObject";
	}
	interface Env {
		CHROMA_API_KEY: string;
		CHROMA_TENANT: string;
		CHROMA_DATABASE: string;
		CHROMA_COLLECTION: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_API_KEY: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		OPENROUTER_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		BETTER_AUTH_URL: string;
		BETTER_AUTH_SECRET: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		VITE_PUBLIC_POSTHOG_KEY: string;
		VITE_PUBLIC_POSTHOG_HOST: string;
		POSTHOG_API_KEY: string;
		CALLBACK_URL: string;
		SANDBOX_SECRET: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		AVATAR_BUCKET: R2Bucket;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CHROMA_API_KEY" | "CHROMA_TENANT" | "CHROMA_DATABASE" | "CHROMA_COLLECTION" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_API_KEY" | "CLOUDFLARE_ACCOUNT_ID" | "OPENROUTER_API_KEY" | "ANTHROPIC_API_KEY" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GITHUB_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "VITE_PUBLIC_POSTHOG_KEY" | "VITE_PUBLIC_POSTHOG_HOST" | "POSTHOG_API_KEY" | "CALLBACK_URL" | "SANDBOX_SECRET">> {}
}
