/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 5eee6791ab1b8c3f5fbd697565aadde7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyMCP";
	}
	interface Env {
		OAUTH_KV: KVNamespace;
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
		WEB_APP: Fetcher /* lored-web */;
	}
}
interface Env extends Cloudflare.Env {}
